# Site
name: 'The CAD Coder'
description: 'Free Visual Basic for Application tutorial for Solidworks 3d software macro programming.'
# logo: 'assets/images/favicon.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: ''
disqus: 'demowebsite'
email: 'thecadcoder@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Admin
      site:           https://thecadcoder.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am the author of The CAD Coder, the blog you're currently reading. I hope you like it!"
      email:          thecadcoder@gmail.com
      twitter:        https://twitter.com/CadCoder
      facebook:       https://www.facebook.com/thecadcoder

#    jane:
#      name:           Jane
#      site:           https://www.wowthemes.net
#      avatar:         /assets/images/avatar2.jpg
#      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
#      email:          fakemail@gmail.com
#      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      permalink: /:categories/:title
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Google Analytics
google_analytics : UA-117501871-2

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: thecadcoder@gmail.com
  facebook: thecadcoder
#  github: The-CAD-Coder
  twitter: CadCoder
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
